import { NextResponse, after } from "next/server";
import { isLocale, type Locale } from "@/i18n/config";
import {
  createProductCheckoutSession,
  createGuideCheckoutSession,
  type CheckoutSessionResult,
} from "@/lib/stripe/create-checkout";
import { recordContactEvent } from "@/lib/contacts/events";
import { getContactById } from "@/lib/contacts/ensure";
import { schedulePrePaymentReminders } from "@/lib/contacts/reminders";
import { sendMetaEvent } from "@/lib/meta/capi";
import { metaUserFromRequest } from "@/lib/meta/request";

export async function POST(request: Request) {
  try {
    const body = (await request.json()) as {
      productIds?: string[];
      guideIds?: string[];
      locale?: string;
      contactId?: string;
      /** Generated by the browser pixel so Meta deduplicates the event pair. */
      metaEventId?: string;
    };

    const productIds = body.productIds?.filter(Boolean) ?? [];
    const guideIds = body.guideIds?.filter(Boolean) ?? [];
    const locale = body.locale && isLocale(body.locale) ? (body.locale as Locale) : "bg";
    const contactId = body.contactId?.trim();

    if (productIds.length > 0 && guideIds.length > 0) {
      return NextResponse.json(
        { message: "Cannot checkout products and guides together" },
        { status: 400 },
      );
    }

    let contactEmail: string | null = null;
    let contactName: string | null = null;

    if (contactId && productIds.length > 0) {
      const contact = await getContactById(contactId);
      if (contact) {
        contactEmail = contact.email;
        contactName = contact.name;
        void recordContactEvent({
          contactId,
          eventType: "checkout_started",
          source: "site",
          metadata: { product_ids: productIds, locale },
        }).catch(() => {});
        if (contact.payment_status !== "paid") {
          void schedulePrePaymentReminders(contact, locale).catch(() => {});
        }
      }
    }

    if (productIds.length === 0 && guideIds.length === 0) {
      return NextResponse.json({ message: "No items selected" }, { status: 400 });
    }

    const browser = metaUserFromRequest(request);
    const isGuide = guideIds.length > 0;
    const itemIds = isGuide ? guideIds : productIds;
    // Pixel cookies ride along in session metadata so the webhook can attribute
    // the Purchase event back to the ad click.
    const tracking = { fbp: browser.fbp, fbc: browser.fbc };
    const session: CheckoutSessionResult = isGuide
      ? await createGuideCheckoutSession(guideIds, locale, contactId, tracking)
      : await createProductCheckoutSession(productIds, locale, contactId, tracking);

    // Server half of InitiateCheckout — exact Stripe amount, survives ad blockers.
    // `after` keeps the redirect instant while the request stays alive for Meta.
    const referer = request.headers.get("referer");
    after(async () => {
      await sendMetaEvent({
        eventName: "InitiateCheckout",
        eventId: body.metaEventId?.trim() || null,
        eventSourceUrl: referer,
        source: "browser",
        user: {
          ...browser,
          email: contactEmail,
          firstName: contactName?.split(/\s+/)[0] ?? null,
          externalId: contactId ?? null,
        },
        custom: {
          value: session.amountCents != null ? session.amountCents / 100 : null,
          currency: session.currency,
          contentIds: itemIds,
          contentType: "product",
          numItems: itemIds.length,
        },
      });
    });

    return NextResponse.json({ url: session.url });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Checkout failed";
    return NextResponse.json({ message }, { status: 400 });
  }
}
